Indicate secret emptiness

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -38,6 +38,19 @@ jobs:
     - name: Dump github ref
       run: echo "$GITHUB_REF"
 
+    - name: Test secrets
+      run: |
+        if [ -z ${{ secrets.V3IO_API }} ];
+          then
+                echo "missing V3IO_API secret";
+                exit 1;
+        fi
+        if [ -z ${{ secrets.V3IO_ACCESS_KEY }} ];
+          then
+                echo "missing V3IO_ACCESS_KEY secret";
+                exit 1;
+        fi
+
     - uses: actions/setup-go@v2
       with:
         go-version: "^1.14.0"
